"""Tests for OpenShell protection (app/openshell.py + security wiring).

The security agent's product/doc fetches run inside a managed OpenShell
sandbox when the fox-services broker (and the gateway behind it) answers,
and direct otherwise -- the assessment records which path served each page.
These tests pin: the C13-C15 catalogue entries, the deterministic policy,
both fetch paths, and the report posture lines.
"""
import json
import os
import tempfile
import unittest
from unittest import mock

# Pin the database before app.database is imported: a module that omits
# this can inherit data/akm.db and write test rows into the live store.
os.environ["AKM_DATABASE_URL"] = os.environ.get("AKM_TEST_DB") or (
    "sqlite:///" + os.path.join(tempfile.mkdtemp(prefix="akm-openshell-"), "test.db"))

from app import openshell as osh  # noqa: E402
from app import security as sec  # noqa: E402
from app import threatpack as tp  # noqa: E402


class FakeResp:
    def __init__(self, status_code=200, body=None):
        self.status_code = status_code
        self._body = body if body is not None else {}

    def raise_for_status(self):
        if self.status_code >= 400:
            raise RuntimeError(f"HTTP {self.status_code}")

    def json(self):
        if isinstance(self._body, Exception):
            raise self._body
        return self._body


CURL_OUT = ("HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\n"
            "\r\n<html><head><title>Vendor Docs</title></head>"
            "<body><p>Hello world, this is the product page.</p></body></html>")


class TestOpenshellControls(unittest.TestCase):
    def test_c13_c15_are_first_class_controls(self):
        by_id = {c["id"]: c for c in sec.control_catalog()}
        for cid in ("C13", "C14", "C15"):
            self.assertIn(cid, by_id, cid)
            c = by_id[cid]
            self.assertTrue(c["name"])
            self.assertGreater(c["efficacy"], 0)
            self.assertLess(c["efficacy"], 1)
            self.assertIn("OpenShell", c["standard"], cid)
            for tid in c["threats"]:
                self.assertIn(tid, sec._THREAT_IDS, f"{cid} -> {tid}")

    def test_pack_version_bumped_for_new_controls(self):
        self.assertEqual(tp.PACK_VERSION, "2.1.0")


class TestPolicyYaml(unittest.TestCase):
    def test_pinned_format(self):
        y = osh.generate_policy_yaml("Acme", "confidential_data",
                                     ["https://docs.acme.example/guide"])
        self.assertEqual(y, """\
# OpenShell sandbox policy generated by AKM -- apply with:
#   openshell policy set --file openshell-policy.yaml
# Widening egress or filesystem access should be proved first:
#   openshell policy prove --file openshell-policy.yaml
policy_version: "1"
product: "Acme"
exposure: "confidential_data"
filesystem:
  read: ["/workspace", "/tmp"]
  deny: ["~/.aws", "~/.config", "~/.ssh", "/etc/shadow", "/root"]
network:
  default: deny
  allow:
    - host: "docs.acme.example"
      methods: [GET]
      reason: fetched during assessment
process:
  deny: [ssh, scp, nc, ncat]
credentials:
  broker: true  # agents never hold secrets; the gateway injects them per approved endpoint
review:
  required: true  # restricted/confidential: a human approves any widening
""")

    def test_deterministic_under_reorder_dupe_and_case(self):
        a = osh.generate_policy_yaml("P", "internal",
                                     ["https://B.example/x", "https://a.example/y"])
        b = osh.generate_policy_yaml("P", "internal",
                                     ["https://A.EXAMPLE/y", "https://b.example/x",
                                      "https://a.example/y", "not a url",
                                      "ftp://c.example/z"])
        self.assertEqual(a, b)

    def test_public_tier_needs_no_review_and_empty_hosts_noted(self):
        y = osh.generate_policy_yaml("P", "public", [])
        self.assertIn("required: false", y)
        self.assertIn("allow: []", y)

    def test_quoting_survives_quotes_and_newlines(self):
        y = osh.generate_policy_yaml('W"id\nget', "internal", [])
        self.assertIn('product: "W\\"id\\nget"', y)


class TestBrokerClient(unittest.TestCase):
    def test_status_down_never_raises(self):
        with mock.patch("requests.get", side_effect=ConnectionError("nope")):
            st = osh.broker_status()
        self.assertFalse(st["reachable"])
        self.assertIn("error", st)

    def test_status_up_passes_through(self):
        body = {"gateway": {"reachable": True}, "sandboxes": [{"name": "s1"}]}
        with mock.patch("requests.get", return_value=FakeResp(200, body)):
            st = osh.broker_status()
        self.assertTrue(st["reachable"])
        self.assertEqual(st["sandboxes"], [{"name": "s1"}])

    def test_exec_503_means_gateway_down(self):
        with mock.patch("requests.post", return_value=FakeResp(503, {"detail": "down"})):
            with self.assertRaises(osh.OpenshellUnavailable):
                osh.broker_exec(["echo", "hi"])

    def test_exec_503_error_key_also_read(self):
        with mock.patch("requests.post", return_value=FakeResp(503, {"error": "down"})):
            with self.assertRaisesRegex(osh.OpenshellUnavailable, "down"):
                osh.broker_exec(["echo", "hi"])

    def test_exec_transport_error_means_broker_down(self):
        with mock.patch("requests.post", side_effect=TimeoutError("t")):
            with self.assertRaises(osh.OpenshellUnavailable):
                osh.broker_exec(["echo", "hi"])

    def test_exec_nonzero_exit_is_a_failure(self):
        with mock.patch("requests.post",
                        return_value=FakeResp(200, {"ok": True, "exit_code": 3,
                                                    "stdout": "", "stderr": "boom",
                                                    "sandbox": "s"})):
            with self.assertRaises(osh.OpenshellUnavailable):
                osh.broker_exec(["false"])

    def test_exec_ok_parses(self):
        with mock.patch("requests.post",
                        return_value=FakeResp(200, {"ok": True, "exit_code": 0,
                                                    "stdout": "hi", "stderr": "",
                                                    "sandbox": "s"})) as m:
            res = osh.broker_exec(["echo", "hi"], sandbox="s", timeout_s=5)
        self.assertEqual(res["stdout"], "hi")
        self.assertEqual(res["sandbox"], "s")
        sent = m.call_args[1]["json"]
        self.assertEqual(sent["command"], ["echo", "hi"])
        self.assertEqual(sent["sandbox"], "s")

    def test_fetch_rejects_non_http_without_network(self):
        with mock.patch("requests.post") as m:
            self.assertFalse(osh.fetch_url("notaurl")["ok"])
            self.assertFalse(osh.fetch_url("ftp://h/x")["ok"])
            m.assert_not_called()

    def test_fetch_parses_sandboxed_curl_output(self):
        with mock.patch("app.openshell.broker_exec",
                        return_value={"ok": True, "exit_code": 0,
                                      "stdout": CURL_OUT, "stderr": "",
                                      "sandbox": "s"}):
            res = osh.fetch_url("https://vendor.example/docs")
        self.assertTrue(res["ok"])
        self.assertEqual(res["status_code"], 200)
        self.assertEqual(res["ctype"], "text/html")
        self.assertIn("Vendor Docs", res["body"])

    def test_fetch_broker_down_is_not_ok(self):
        with mock.patch("app.openshell.broker_exec",
                        side_effect=osh.OpenshellUnavailable("down")):
            self.assertFalse(osh.fetch_url("https://vendor.example/docs")["ok"])


class TestFetchPageSummary(unittest.TestCase):
    def test_sandboxed_path_marks_and_parses(self):
        with mock.patch("app.openshell.fetch_url",
                        return_value={"ok": True, "status_code": 200,
                                      "ctype": "text/html", "body":
                                      "<html><head><title>T</title></head>"
                                      "<body><p>words here hello</p></body></html>"}):
            out = sec.fetch_page_summary("https://vendor.example/x")
        self.assertTrue(out["sandbox"])
        self.assertEqual(out["title"], "T")
        self.assertIn("words here", out["excerpt"])
        self.assertTrue(out["status"].startswith("sandboxed"))

    def test_fallback_to_direct_marks_unsandboxed(self):
        with mock.patch("app.openshell.fetch_url",
                        side_effect=osh.OpenshellUnavailable("down")):
            with mock.patch("requests.get") as g:
                g.return_value.status_code = 200
                g.return_value.headers = {"content-type": "text/html"}
                g.return_value.text = "<html><body><p>direct words</p></body></html>"
                out = sec.fetch_page_summary("https://vendor.example/x")
        self.assertFalse(out["sandbox"])
        self.assertIn("direct words", out["excerpt"])
        self.assertTrue(out["status"].startswith("fetched"))

    def test_unreachable_keeps_contract(self):
        with mock.patch("app.openshell.fetch_url",
                        side_effect=osh.OpenshellUnavailable("down")):
            with mock.patch("requests.get", side_effect=ConnectionError("no")):
                out = sec.fetch_page_summary("https://vendor.example/x")
        self.assertFalse(out["sandbox"])
        self.assertTrue(out["status"].startswith("unreachable:"))


class TestAssessmentBlock(unittest.TestCase):
    def test_block_aggregates_and_filters_controls(self):
        pages = [
            {"url": "https://a.example/1", "excerpt": "x", "sandbox": True},
            {"url": "https://b.example/2", "excerpt": "y", "sandbox": False},
        ]
        block = osh.assessment_openshell_block(pages, "P", "internal",
                                               ["C13", "C02", "C99"])
        self.assertTrue(block["sandbox_used"])
        self.assertEqual(block["sandbox_pages"], 1)
        self.assertEqual(block["controls"], ["C13"])
        self.assertEqual(block["policy_version"], "1")
        self.assertIn('host: "a.example"', block["policy_yaml"])
        self.assertIn('host: "b.example"', block["policy_yaml"])


class TestPostureLines(unittest.TestCase):
    def test_active_controls_named_and_sandbox_counted(self):
        lines = sec.openshell_posture_lines(
            ["C02", "C13"], [{"url": "u", "sandbox": True}],
            {"sandbox_used": True, "sandbox_pages": 1})
        text = "\n".join(lines)
        self.assertIn("C13", text)
        self.assertIn("1 of 1", text)
        self.assertNotIn("unsandboxed", text)

    def test_no_controls_no_sandbox_says_so(self):
        lines = sec.openshell_posture_lines([], [], {"sandbox_used": False})
        text = "\n".join(lines)
        self.assertIn("None of the OpenShell controls", text)
        self.assertIn("records", text)

    def test_policy_lines_shape(self):
        self.assertEqual(sec.openshell_policy_lines({}), [])
        self.assertEqual(sec.openshell_policy_lines({"policy_yaml": ""}), [])
        lines = sec.openshell_policy_lines({"policy_yaml": "a: 1\n",
                                            "policy_version": "1"})
        self.assertEqual(lines[0], "")
        self.assertIn("policy v1", lines[1])
        self.assertEqual(lines[3], "```yaml")
        self.assertEqual(lines[-1], "```")


if __name__ == "__main__":
    unittest.main()
